### Obtener todas las tareas
GET http://127.0.0.1:8000/api/tareas/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZGphbmdvZnJvbnRlbmQiLCJhdWQiOiJkamFuZ29mcm9udGVuZCIsImF1dGhfdGltZSI6MTc3Mjc0NjgzMiwidXNlcl9pZCI6IjltMVg3TWJKdGRYbVpyOTM5QzUxdUFmVDBYSTMiLCJzdWIiOiI5bTFYN01iSnRkWG1acjkzOUM1MXVBZlQwWEkzIiwiaWF0IjoxNzcyNzQ2ODMyLCJleHAiOjE3NzI3NTA0MzIsImVtYWlsIjoic2FtdWVsOUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsic2FtdWVsOUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.cEs1fmbzAfzEycpgCF27Ga5NJB6CqzRedIlbWr6uYlXS6rpqTfN3TvCqzvMhn-eOWMwCu1K1Ce1UT6uxuEGiI9z1rLxeV8Fa4njtn5J9GFSlKN57CODxH7h336kSOSviu1XV8FFaM5YB_lfPk79qOlpMb6r-qPgT0sdpSWYUIueLCXpJoRvPtn4vgcrn1AjmABeNLkMLOi4jIEO5vFVwzOVTFdmp8tWknE1QUVK8XMrHmHp_erXDYYak-CpCuAyZ4BdSay1IS6IwXHV9Uvqy6ghctlFKRfjb8dbo3RT9k9EbfWA9eNt7z0IDQMx704wq5ZKSYPbwMKPpNl0xT3njIw
Content-Type: application/json

{
    "email": "samuel9@gmail.com",
    "password": "123456"
}

### 2. Iniciar sesión para conseguir el Token (POST)
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "samuel9@gmail.com",
    "password": "123456"
}

### 3. Crear una tarea USANDO EL TOKEN (POST)
POST http://127.0.0.1:8000/api/tareas/
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJhYWM0MWY3NTA4OGZlOGUwOWEwN2Q0NDRjZmQ2YjhjZTQ4MTJhMzEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZGphbmdvZnJvbnRlbmQiLCJhdWQiOiJkamFuZ29mcm9udGVuZCIsImF1dGhfdGltZSI6MTc3Mjc0NTcxMSwidXNlcl9pZCI6IkhRWFh1NlBEcEdUZENjeFFlTUlhYk85VkJUazEiLCJzdWIiOiJIUVhYdTZQRHBHVGRDY3hRZU1JYWJPOVZCVGsxIiwiaWF0IjoxNzcyNzQ1NzExLCJleHAiOjE3NzI3NDkzMTEsImVtYWlsIjoic2FtdWVsMTBAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInNhbXVlbDEwQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.Ve923uLz0-QdV3IODOGK43-OpQ8srL16p6l34g4TPrYLg_yfsUwXLDyLUht6ToX7kHF_pOCuj6pTw3k_re5pnDebIdQ-KvnQ_5r0rt3tSmhU-nYZhE5gsehcZIvGxodrAMkoLlmNAg8nBAni0_QvLbSDMiETVQVJdlyZ1FmMRkEmXNVEV9ln2BNr7yFyZTfrCJQFt3MO0uvFasc2CkppE9rawwuPEZrd5oSZpe-o1JhoNOGh8II8WYmFjAcMv1M-iQCUmWHJWMEzGEI6ut7ul6efukjIJMz9s7mt_G19GiOm94jA147yqSDMP-sxcayo-ZzM6LFN3UJphmjKBz_IEQ

{
    "titulo": "Tarea con API Segura",
    "descripcion": "Mi segunda tarea usando JWT de Firebase"
}
### subir imagen de perfil a cloudinary
POST http://127.0.0.1:8000/api/perfil/foto/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZGphbmdvZnJvbnRlbmQiLCJhdWQiOiJkamFuZ29mcm9udGVuZCIsImF1dGhfdGltZSI6MTc3NDA0NjkwMCwidXNlcl9pZCI6IjltMVg3TWJKdGRYbVpyOTM5QzUxdUFmVDBYSTMiLCJzdWIiOiI5bTFYN01iSnRkWG1acjkzOUM1MXVBZlQwWEkzIiwiaWF0IjoxNzc0MDQ2OTAwLCJleHAiOjE3NzQwNTA1MDAsImVtYWlsIjoic2FtdWVsOUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsic2FtdWVsOUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mDeWBlN99NO_Dge4S1YffRN7j615mDNgt_RTY9aV8AOQA7qcburJFF2Kivt5K3B6c0WCWmflv_3SuG9zl2TmanspXJTuHJAfT_JPg7i91waTdDzXNvpef7XdPzeCCOpzuheOeKr-D_1tFlr_k05NF2rNA8rZ7glivnqAw9MI6WzAh8zXw4SJ8r6BQUcXIbxTCl_06QWUvNVWu-6cJ6qUy4Y2vq5Fy6hlc1p-Nmbm-iYnsKS7JqdDRlDZcmzUENQDW28t_XSpYpzLUPhkyBEtCY3SzxhBFcm5Ad5bHhv_LknhiU10e_YZQdk6INegyQ15nRAz5mKcbApqIRxuk0ntEw
Content-Type: multipart/form-data; boundary=MiBoundary

--MiBoundary
Content-Disposition: form-data; name="imagen"; filename="avatar.jpg"
Content-Type: image/jpeg

< C:\Users\USUARIO\OneDrive\Documentos\QUINTO TRIMESTRE\CRISTIAN MARTINEZ\backend\avatar.jpg

--MiBoundary--
###ver infromacion de perfil
GET http://127.0.0.1:8000/api/perfil/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjczMmNhOTY3MTNiMWRkMTcyMzg1MDg0Y2U5ZjQzODFhZDAwY2VjZTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZGphbmdvZnJvbnRlbmQiLCJhdWQiOiJkamFuZ29mcm9udGVuZCIsImF1dGhfdGltZSI6MTc3NDA0NjkwMCwidXNlcl9pZCI6IjltMVg3TWJKdGRYbVpyOTM5QzUxdUFmVDBYSTMiLCJzdWIiOiI5bTFYN01iSnRkWG1acjkzOUM1MXVBZlQwWEkzIiwiaWF0IjoxNzc0MDQ2OTAwLCJleHAiOjE3NzQwNTA1MDAsImVtYWlsIjoic2FtdWVsOUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsic2FtdWVsOUBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.mDeWBlN99NO_Dge4S1YffRN7j615mDNgt_RTY9aV8AOQA7qcburJFF2Kivt5K3B6c0WCWmflv_3SuG9zl2TmanspXJTuHJAfT_JPg7i91waTdDzXNvpef7XdPzeCCOpzuheOeKr-D_1tFlr_k05NF2rNA8rZ7glivnqAw9MI6WzAh8zXw4SJ8r6BQUcXIbxTCl_06QWUvNVWu-6cJ6qUy4Y2vq5Fy6hlc1p-Nmbm-iYnsKS7JqdDRlDZcmzUENQDW28t_XSpYpzLUPhkyBEtCY3SzxhBFcm5Ad5bHhv_LknhiU10e_YZQdk6INegyQ15nRAz5mKcbApqIRxuk0ntEw